
[tool.black]
line-length = 100
target-version = ['py311']

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
disallow_untyped_defs = true
strict_optional = true
warn_unused_ignores = true
warn_return_any = true
show_error_codes = true

[tool.coverage.run]
branch = true
source = [
    "core"
]

[tool.coverage.report]
show_missing = true
skip_covered = true