name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage mypy flake8

    - name: Run Flake8
      run: flake8 mtg_ai tests

    - name: Run Mypy
      run: mypy mtg_ai tests

    - name: Run Unit Tests and Coverage
      run: |
        coverage run --source=mtg_ai -m unittest discover -s tests
        coverage report
        coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml